import {
  heroArrowsRightLeft,
  heroArrowsUpDown,
  heroArrowTrendingUp,
  heroBellAlert,
  heroBookOpen,
  heroBuildingOffice2,
  heroCalendarDays,
  heroCreditCard,
  heroBanknotes,
  heroChatBubbleLeftRight,
  heroClipboardDocumentCheck,
  heroClipboardDocumentList,
  heroCube,
  heroIdentification,
  heroRectangleGroup,
  heroSquares2x2,
  heroShoppingCart,
  heroTruck,
  heroUsers,
} from '@ng-icons/heroicons/outline';

export const moduleIcons: Readonly<Record<string, string>> = {
  overview: heroRectangleGroup,
  sales: heroShoppingCart,
  finance: heroBanknotes,
  procurement: heroTruck,
  inventory: heroCube,
  people: heroUsers,
  customerList: heroIdentification,
  contactHistory: heroChatBubbleLeftRight,
  paymentMatching: heroArrowsRightLeft,
  receivables: heroArrowTrendingUp,
  payables: heroCreditCard,
  ledger: heroBookOpen,
  closing: heroCalendarDays,
  dunning: heroBellAlert,
  orderHandling: heroClipboardDocumentList,
  supplierList: heroBuildingOffice2,
  purchaseOrders: heroClipboardDocumentCheck,
  stockLevels: heroSquares2x2,
  movements: heroArrowsUpDown,
};
