import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build, transform } from 'esbuild';
import ts from 'typescript';
import postcss from 'postcss';
import tailwindcss from '@tailwindcss/postcss';

const here = (path) => fileURLToPath(new URL(path, import.meta.url));
const outDir = process.env.LW_FRAME_KIT_OUT ?? here('./dist');
const version = JSON.parse(readFileSync(here('./package.json'), 'utf8')).version;
const banner = (artifact) =>
  `/* @loomweaver/frame-kit ${version} — ${artifact}. Generated by build.mjs; do not edit. ` +
  `Serve the dist/ files same-origin under /frame-kit/. */`;

mkdirSync(outDir, { recursive: true });

await build({
  entryPoints: [here('../shell/src/lib/elements/lw-elements.frame.ts')],
  outfile: join(outDir, 'lw-elements.global.js'),
  bundle: true,
  format: 'iife',
  minify: true,
  target: 'es2022',
  alias: { '@loomweaver/plugin-sdk': here('../plugin-sdk/src/index.ts') },
  banner: { js: banner('lw-elements.global.js') },
  absWorkingDir: here('.'),
});

function emitGlobalScriptDeclaration(entry) {
  const emitted = new Map();
  const program = ts.createProgram([entry], {
    declaration: true,
    emitDeclarationOnly: true,
    stripInternal: true,
    skipLibCheck: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    module: ts.ModuleKind.ESNext,
  });
  program.emit(undefined, (name, text) => emitted.set(name, text), undefined, true);

  const declaration = [...emitted.entries()].find(([name]) =>
    name.endsWith('lw-elements.frame.d.ts'),
  );
  if (!declaration) {
    throw new Error('no declaration emitted for the frame entry');
  }
  const asScript = declaration[1]
    .replace(/^export declare /gm, 'declare ')
    .replace(/^export /gm, '')
    .replace(/^export \{\};?\n?/gm, '')
    .trim();
  if (/^(import|export)\b/m.test(asScript)) {
    throw new Error(
      'the frame declaration reaches beyond its own shapes — it must stay self-contained',
    );
  }
  return `${asScript}\n\ndeclare const LwFrame: LwFrameApi;\n`;
}

writeFileSync(
  join(outDir, 'lw-frame.d.ts'),
  `${banner('lw-frame.d.ts')}\n${emitGlobalScriptDeclaration(here('../shell/src/lib/elements/lw-elements.frame.ts'))}`,
);

await build({
  entryPoints: ['penpal'],
  outfile: join(outDir, 'penpal.global.js'),
  bundle: true,
  format: 'iife',
  globalName: 'Penpal',
  minify: true,
  target: 'es2022',
  banner: { js: banner('penpal.global.js') },
  absWorkingDir: here('.'),
});

const cssEntry = here('./src/lw-frame.entry.css');
const compiled = await postcss([tailwindcss({ base: dirname(cssEntry) })]).process(
  readFileSync(cssEntry, 'utf8'),
  { from: cssEntry },
);
const minified = await transform(compiled.css, { loader: 'css', minify: true });
writeFileSync(join(outDir, 'lw-frame.css'), `${banner('lw-frame.css')}\n${minified.code}`);

console.log(`@loomweaver/frame-kit ${version} → ${outDir}`);
