import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build, transform } from 'esbuild';
import ts from 'typescript';
import postcss from 'postcss';
import tailwindcss from '@tailwindcss/postcss';
import { declarationAsScript } from './declaration-as-script.mjs';

const here = (path) => fileURLToPath(new URL(path, import.meta.url));
const outDir = process.env.LW_FRAME_KIT_OUT ?? here('./dist');
const version = JSON.parse(readFileSync(here('./package.json'), 'utf8')).version;
const frameEntry = here('../shell/src/lib/surface-kit/surface-kit.frame.ts');
const banner = (artifact) =>
  `/* @loomweaver/frame-kit ${version} — ${artifact}. Generated by build.mjs; do not edit. ` +
  `Serve the dist/ files same-origin under /frame-kit/. */`;

async function bundleElements() {
  await build({
    entryPoints: [frameEntry],
    outfile: join(outDir, 'lw-elements.global.js'),
    bundle: true,
    format: 'iife',
    minify: true,
    target: 'es2022',
    alias: { '@loomweaver/plugin-sdk': here('../plugin-sdk/src/index.ts') },
    banner: { js: banner('lw-elements.global.js') },
    absWorkingDir: here('.'),
  });
}

function emitGlobalScriptDeclaration(entry) {
  const emitted = new Map();
  const program = ts.createProgram([entry], {
    declaration: true,
    emitDeclarationOnly: true,
    stripInternal: true,
    skipLibCheck: true,
    strict: true,
    target: ts.ScriptTarget.ES2022,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    module: ts.ModuleKind.ESNext,
  });
  program.emit(undefined, (name, text) => emitted.set(name, text), undefined, true);

  const declaration = [...emitted].find(([name]) =>
    name.endsWith('surface-kit.frame.d.ts'),
  );
  if (!declaration) {
    throw new Error('no declaration emitted for the frame entry');
  }
  return `${declarationAsScript(declaration[1])}\n\ndeclare const LwFrame: LwFrameApi;\n`;
}

function writeDeclaration() {
  writeFileSync(
    join(outDir, 'lw-frame.d.ts'),
    `${banner('lw-frame.d.ts')}\n${emitGlobalScriptDeclaration(frameEntry)}`,
  );
}

async function vendorGlobal(entryPoint, artifact, globalName) {
  await build({
    entryPoints: [entryPoint],
    outfile: join(outDir, artifact),
    bundle: true,
    format: 'iife',
    globalName,
    minify: true,
    target: 'es2022',
    banner: { js: banner(artifact) },
    absWorkingDir: here('.'),
  });
}

async function compileStyles() {
  const cssEntry = here('./src/lw-frame.entry.css');
  const compiled = await postcss([tailwindcss({ base: dirname(cssEntry) })]).process(
    readFileSync(cssEntry, 'utf8'),
    { from: cssEntry },
  );
  const minified = await transform(compiled.css, { loader: 'css', minify: true });
  writeFileSync(join(outDir, 'lw-frame.css'), `${banner('lw-frame.css')}\n${minified.code}`);
}

mkdirSync(outDir, { recursive: true });
await bundleElements();
writeDeclaration();
await vendorGlobal('@zumer/snapdom', 'snapdom.global.js', 'LwSnapdom');
await vendorGlobal('penpal', 'penpal.global.js', 'Penpal');
await compileStyles();

console.log(`@loomweaver/frame-kit ${version} → ${outDir}`);
