import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { transform } from 'esbuild';
import postcss from 'postcss';
import tailwindcss from '@tailwindcss/postcss';

const here = (path) => fileURLToPath(new URL(path, import.meta.url));
const outDir = process.env.LW_SHELL_STYLES_OUT ?? here('../../../dist/libs/core/shell/styles');

const entry = here('./src/lib/styles/shell.entry.css');
const compiled = await postcss([tailwindcss({ base: dirname(entry) })]).process(
  readFileSync(entry, 'utf8'),
  { from: entry },
);
const minified = await transform(compiled.css, { loader: 'css', minify: true });

const banner =
  `/* @loomweaver/shell — shell.css. Generated by build-styles.mjs; do not edit.\n` +
  `   The full stylesheet: design tokens, the .lw-* class contracts and every utility the shell's\n` +
  `   own templates use. Import it when you do not run Tailwind yourself; import styles/theme.css\n` +
  `   instead when you do.\n` +
  `   Everything here sits in cascade layers, and unlayered CSS outranks layered CSS whatever its\n` +
  `   specificity — so import another framework INTO A LAYER, or its element resets will beat our\n` +
  `   component classes: @import 'bootstrap/…/bootstrap.css' layer(vendor); */`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, 'shell.css'), `${banner}\n${minified.code}\n`);

console.log(
  `@loomweaver/shell → ${join(outDir, 'shell.css')} (${(minified.code.length / 1024).toFixed(1)} KB)`,
);
