import starlight from '@astrojs/starlight';
import { defineConfig, passthroughImageService } from 'astro/config';

export default defineConfig({
  site: 'https://loomweaver.dev',
  // Passthrough keeps sharp (and its LGPL libvips binary) out of the tree; the site
  // ships two brand PNGs, so optimisation buys nothing worth a copyleft dependency.
  image: { service: passthroughImageService() },
  integrations: [
    starlight({
      title: 'LoomWeaver',
      description:
        'A domain-agnostic plugin & UI platform. Products run as plugin bundles on top of it; the platform itself contains zero domain logic.',
      favicon: '/loomweaver-icon.png',
      logo: {
        src: './generated/assets/loomweaver-icon.png',
        alt: 'LoomWeaver',
      },
      customCss: ['./src/styles/brand.css'],
      // The footer carries the legal links and the consent banner. Starlight renders it on every
      // page, the splash landing page included, so overriding it reaches the whole site at once.
      // Umami itself is not loaded here: the banner appends the script only once somebody agrees.
      components: {
        Footer: './src/components/Footer.astro',
      },
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/yesbert/loomweaver',
        },
      ],
      sidebar: [
        { label: 'Overview', link: '/overview/' },
        {
          label: 'Guides',
          items: [
            { label: 'Architecture', link: '/architecture/' },
            { label: 'Getting started', link: '/getting-started/' },
            { label: 'Manual setup', link: '/manual-setup/' },
            { label: 'Samples', link: '/samples/' },
            { label: 'Authoring a weaver', link: '/authoring-a-weaver/' },
            { label: 'Building a distribution', link: '/building-a-distribution/' },
            { label: 'The plugin system', link: '/plugins/' },
            { label: 'Scaffolding', link: '/scaffolding/' },
            { label: 'Backend integration', link: '/backend-integration/' },
          ],
        },
        // Listed rather than autogenerated: Starlight derives `autogenerate` from its own
        // collection, and we load the synced docs with our own glob() loader, so it matched
        // nothing and this group rendered empty. sync-docs.mjs fails the build if a file under
        // docs/reference/ is missing here, which is the guard the autogeneration used to be.
        {
          label: 'Reference',
          items: [
            { label: 'Shell anatomy', link: '/reference/shell-anatomy/' },
            { label: 'Host services', link: '/reference/host-services/' },
            { label: 'Access gating', link: '/reference/access-gating/' },
            { label: 'Routing', link: '/reference/routing/' },
            { label: 'Callable commands', link: '/reference/callable-commands/' },
            { label: 'Agent tools', link: '/reference/agent-tools/' },
            { label: 'Design tokens', link: '/reference/design-tokens/' },
            { label: 'Accessibility', link: '/reference/accessibility/' },
            { label: 'Operations', link: '/reference/operations/' },
          ],
        },
        {
          label: 'For AI assistants',
          items: [
            { label: 'llms.txt', link: '/llms.txt', attrs: { target: '_blank' } },
            { label: 'llms-full.txt', link: '/llms-full.txt', attrs: { target: '_blank' } },
          ],
        },
      ],
    }),
  ],
});
