/* The navigation tree, in a module of its own because two things read it: astro.config.mjs, which
   renders it, and the head component, which turns the group a page sits in into a BreadcrumbList.
   Declared once, so a breadcrumb can never disagree with the sidebar a reader is looking at.

   sync-docs.mjs fails the build when a page under docs/ is missing from this list — that check
   reads this file, and is the reason the tree is hand-kept rather than autogenerated. */
export const sidebar = [
  { label: 'Overview', link: '/overview/' },
  { label: 'Changelog', link: '/changelog/' },
  {
    label: 'Guides',
    items: [
      { label: 'Architecture', link: '/architecture/' },
      { label: 'Getting started', link: '/getting-started/' },
      { label: 'Building with an AI assistant', link: '/building-with-an-assistant/' },
      { label: 'The workbench your users get', link: '/the-workbench/' },
      { label: 'Manual setup', link: '/manual-setup/' },
      { label: 'Samples', link: '/samples/' },
      { label: 'The plugin system', link: '/plugins/' },
      { label: 'Scaffolding', link: '/scaffolding/' },
      { label: 'AG-UI agents', link: '/ag-ui-agents/' },
      { label: 'Backend integration', link: '/backend-integration/' },
    ],
  },
  {
    label: 'Authoring a weaver',
    collapsed: true,
    items: [
      { label: 'Overview', link: '/authoring-a-weaver/' },
      {
        label: 'Surfaces in a sidebar',
        link: '/weaver/sidebar-surfaces/',
      },
      {
        label: 'A navigation tree in the sidebar',
        link: '/weaver/navigation-tree/',
      },
      { label: 'View state that survives', link: '/weaver/view-state/' },
      { label: 'Unsaved changes', link: '/weaver/unsaved-changes/' },
      { label: "Your plugin's own store", link: '/weaver/plugin-state/' },
      { label: 'Containers', link: '/weaver/containers/' },
      { label: 'The content area', link: '/weaver/content-area/' },
      {
        label: 'Sub-routes and follows',
        link: '/weaver/sub-routes-and-follows/',
      },
      { label: 'Menus', link: '/weaver/menus/' },
      {
        label: 'Sandboxed surfaces',
        link: '/weaver/sandboxed-surfaces/',
      },
      { label: 'Commands and their triggers', link: '/weaver/commands/' },
      { label: 'Access gating', link: '/weaver/access-gating/' },
      { label: 'Icons and theme', link: '/weaver/icons-and-theme/' },
      {
        label: 'Host UI and host facts',
        link: '/weaver/host-ui-and-facts/',
      },
      { label: 'Settings sections', link: '/weaver/settings/' },
      { label: 'Translations', link: '/weaver/i18n/' },
    ],
  },
  {
    label: 'Building a distribution',
    collapsed: true,
    items: [
      { label: 'Overview', link: '/building-a-distribution/' },
      { label: 'Layout', link: '/distribution/layout/' },
      {
        label: 'Content-area routing',
        link: '/distribution/content-routing/',
      },
      { label: 'Workspaces', link: '/distribution/workspaces/' },
      { label: 'Resetting', link: '/distribution/resetting/' },
      {
        label: 'Switching capabilities off',
        link: '/distribution/switching-capabilities-off/',
      },
      {
        label: 'Surface retention',
        link: '/distribution/surface-retention/',
      },
      { label: 'Branding', link: '/distribution/branding/' },
      {
        label: 'Bringing your own CSS framework',
        link: '/distribution/css-frameworks/',
      },
      { label: 'Capabilities', link: '/distribution/capabilities/' },
      { label: 'Auth integration', link: '/distribution/auth/' },
      { label: 'Persistence stores', link: '/distribution/persistence/' },
      {
        label: 'Windows and sync',
        link: '/distribution/windows-and-sync/',
      },
      { label: 'Frame plugins', link: '/distribution/frame-plugins/' },
      { label: 'Plugin store', link: '/distribution/plugin-store/' },
      {
        label: 'Icons, translations and rewording',
        link: '/distribution/icons-and-i18n/',
      },
      {
        label: 'Recomposing host chrome',
        link: '/distribution/recomposing-chrome/',
      },
      { label: 'PWA and delivery', link: '/distribution/pwa/' },
    ],
  },
  {
    label: 'Distribution API',
    collapsed: true,
    items: [
      { label: 'Overview', link: '/distribution-api/' },
      {
        label: 'Composition',
        link: '/distribution-api/composition/',
      },
      {
        label: 'Switches',
        link: '/distribution-api/switches/',
      },
      { label: 'Tabs', link: '/distribution-api/tabs/' },
      { label: 'Panes', link: '/distribution-api/panes/' },
      {
        label: 'Workspaces',
        link: '/distribution-api/workspaces/',
      },
      {
        label: 'Sidebars',
        link: '/distribution-api/sidebars/',
      },
      { label: 'Resetting', link: '/distribution-api/reset/' },
      {
        label: 'Dialogs and toasts',
        link: '/distribution-api/dialogs-and-toasts/',
      },
      {
        label: 'Settings',
        link: '/distribution-api/settings/',
      },
      {
        label: 'Commands',
        link: '/distribution-api/commands/',
      },
      { label: 'Session', link: '/distribution-api/session/' },
      {
        label: 'Appearance',
        link: '/distribution-api/appearance/',
      },
      {
        label: 'Plugins at runtime',
        link: '/distribution-api/plugins-at-runtime/',
      },
      {
        label: 'Windows, sync and updates',
        link: '/distribution-api/windows-and-sync/',
      },
      {
        label: 'A picture of the workbench',
        link: '/distribution-api/capture/',
      },
    ],
  },
  {
    label: 'Concepts',
    items: [
      {
        label: 'Surfaces and panes',
        link: '/concepts/surfaces-and-panes/',
      },
      { label: 'The address', link: '/concepts/the-address/' },
      {
        label: 'Retention and unsaved work',
        link: '/concepts/retention-and-unsaved-work/',
      },
      {
        label: 'Capabilities and trust',
        link: '/concepts/capabilities-and-trust/',
      },
      { label: 'Workspaces', link: '/concepts/workspaces/' },
    ],
  },
  // Listed rather than autogenerated: Starlight derives `autogenerate` from its own
  // collection, and we load the synced docs with our own glob() loader, so it matched
  // nothing and this group rendered empty. sync-docs.mjs fails the build if any page under
  // docs/ is missing from this sidebar, which is the guard the autogeneration used to be.
  {
    label: 'Platform reference',
    items: [
      { label: 'Shell anatomy', link: '/reference/shell-anatomy/' },
      { label: 'Access gating', link: '/reference/access-gating/' },
      { label: 'Routing', link: '/reference/routing/' },
      {
        label: 'Callable commands',
        link: '/reference/callable-commands/',
      },
      { label: 'Agent tools', link: '/reference/agent-tools/' },
      { label: 'Design tokens', link: '/reference/design-tokens/' },
      { label: 'Icons', link: '/reference/icons/' },
      { label: 'Accessibility', link: '/reference/accessibility/' },
      { label: 'Operations', link: '/reference/operations/' },
      { label: 'Glossary', link: '/glossary/' },
    ],
  },
  {
    label: 'For AI assistants',
    items: [
      {
        label: 'llms.txt',
        link: '/llms.txt',
        attrs: { target: '_blank' },
      },
      {
        label: 'llms-full.txt',
        link: '/llms-full.txt',
        attrs: { target: '_blank' },
      },
      {
        label: 'Agent skill',
        link: '/skills/loomweaver/SKILL.md',
        attrs: { target: '_blank' },
      },
    ],
  },
];
